print("Welcome To Exponent And Power Program")
print("Designed,Coded by Ayaan Ansari")
print("EXPONENT AND POWERS PROGRAM")
print("Type the exponent:")
var1 = input()
print("Type the power:")
var2 = input()
ans = int(var1)**int(var2)
print("Your answer is:",ans)
